### ISSUE TITLE
Can't build for Android with 0.6

### ISSUE THREAD

**Issue by 13Flo** [Unity-Technologies/ml-agents#1527]
Since I upgraded to 0.6, I get these errors when trying to build for Android:

`Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
Copyright (C) Microsoft Corporation. All rights reserved.

error CS1703: **Multiple assemblies with equivalent identity have been imported**: 'E:\Unity Projects\Game\Assets\ML-Agents\Plugins\Android\**System.Threading.dll**' and 'E:\Unity\Hub\Editor\2018.3.0f2\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Facades\System.Threading.dll'. **Remove one of the duplicate references.**
error CS1703: Multiple assemblies with equivalent identity have been imported: 'E:\Unity Projects\Game\Assets\ML-Agents\Plugins\Android\**System.Text.Encoding.dll**' and 'E:\Unity\Hub\Editor\2018.3.0f2\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Facades\System.Text.Encoding.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'E:\Unity Projects\Game\Assets\ML-Agents\Plugins\Android\System.Runtime.Numerics.dll' and 'E:\Unity\Hub\Editor\2018.3.0f2\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Facades\System.Runtime.Numerics.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'E:\Unity Projects\Game\Assets\ML-Agents\Plugins\Android\System.Resources.ResourceManager.dll' and 'E:\Unity\Hub\Editor\2018.3.0f2\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Facades\System.Resources.ResourceManager.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'E:\Unity Projects\Game\Assets\ML-Agents\Plugins\Android\System.Reflection.Extensions.dll' and 'E:\Unity\Hub\Editor\2018.3.0f2\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Facades\System.Reflection.Extensions.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'E:\Unity Projects\Game\Assets\ML-Agents\Plugins\Android\System.Diagnostics.Debug.dll' and 'E:\Unity\Hub\Editor\2018.3.0f2\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Facades\System.Diagnostics.Debug.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'E:\Unity Projects\Game\Assets\ML-Agents\Plugins\Android\System.Collections.dll' and 'E:\Unity\Hub\Editor\2018.3.0f2\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Facades\System.Collections.dll'. Remove one of the duplicate references.
error CS1703: Multiple assemblies with equivalent identity have been imported: 'E:\Unity Projects\Game\Assets\ML-Agents\Plugins\Android\System.Collections.Concurrent.dll' and 'E:\Unity\Hub\Editor\2018.3.0f2\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Facades\System.Collections.Concurrent.dll'. Remove one of the duplicate references.`

Any idea how to fix?

![image](https://user-images.githubusercontent.com/146405/50381660-50380400-0641-11e9-94a1-08ecf5cc6d51.png)
![image](https://user-images.githubusercontent.com/146405/50381584-b1f76e80-063f-11e9-9b54-38bbb10ff896.png)
![image](https://user-images.githubusercontent.com/146405/50381586-bcb20380-063f-11e9-95d6-acb30eb2e4ff.png)

**Comment by jamesjxiao** [comment]
i have this problom too, when i upgrade from 2017.3 to 2018.3. so how to slove it~

**Comment by 13Flo** [comment]
I figure out that removing all the System.XXXX.dll from ML-Agents/Plugins/Android fixes the issue.

**Comment by awjuliani** [comment]
Hi @13Flo 

Thanks for pointing this out. We will be updating our inference solution for the next release of ML-Agents, and will ensure it is functional under Android without this issue.

**Comment by awjuliani** [comment]
Hi all. We are now using the internal inference solution. Closing this issue for now. Please feel free to re-open if you deem it necessary.
