### ISSUE TITLE
The type 'IReadOnlyList<T>' exists in both 'ReadOnlyCollectionsInterfaces after upgrading to 0.12

### ISSUE THREAD

**Issue by albertoxamin** [Unity-Technologies/ml-agents#3023]
**Describe the bug**
I just upgraded to 0.12 and after installing barracuda with the package manager i get this error
![image](https://user-images.githubusercontent.com/6067659/70129388-f2989e00-167e-11ea-8bb6-586529a0496a.jpeg)
```
❗️Library/PackageCache/com.unity.barracuda@0.3.2-preview/Barracuda/Plugins/Editor/BarracudaEditor/ONNXModelImporterEditor.cs(103,59):
 error CS0433: The type 'IReadOnlyList<T>' exists in both 'ReadOnlyCollectionsInterfaces,
 Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

❗️Library/PackageCache/com.unity.barracuda@0.3.2-preview/Barracuda/Plugins/Editor/BarracudaEditor/ONNXModelImporterEditor.cs(103,88):
 error CS0433: The type 'IReadOnlyList<T>' exists in both 'ReadOnlyCollectionsInterfaces,
 Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

**Environment (please complete the following information):**
- OS + version: MacOS catalina 10.15.1 (19B88)
- _ML-Agents version_: v0.12
- _TensorFlow version_: 2.0.0

**Comment by surfnerd** [comment]
Hi @albertoxamin,
Are you using any plugins that contain a redefinition of this interface?

**Comment by albertoxamin** [comment]
Nope, these are the only occurrences in the files
![image](https://user-images.githubusercontent.com/6067659/70179885-2c00f600-16df-11ea-8194-5a252fcec14d.jpeg)

**Comment by surfnerd** [comment]
The other definition could be in a `.dll` file as well.  Is there a `.dll` or any plugin that you are using that has the name `ReadOnlyCollectionsInterfaces`

**Comment by albertoxamin** [comment]
Thanks @surfnerd, it was the GitHub plugin, removing it fixed the issue
