### ISSUE TITLE
Video recorder from docs does not work with new ML-Agents v0.13+

### ISSUE THREAD

**Issue by caioc2** [Unity-Technologies/ml-agents#3294]
**Describe the bug**
The [video recorder plugin](https://github.com/Unity-Technologies/video-recorder) does not work with new ML-Agents Singleton Academy setup.

**To Reproduce**
Open any example(Ball3D) and import the video recorder plugin

**Console logs / stack traces**
```
Assets\ML-Agents\VideoRecorder\Scripts\VideoRecorder.cs(63,23): error CS0311: The type 'MLAgents.Academy' cannot be used as type parameter 'T' in the generic type or method 'Object.FindObjectOfType<T>()'. There is no implicit reference conversion from 'MLAgents.Academy' to 'UnityEngine.Object'.
```

**Environment:**
- _ML-Agents version_: v0.13 and later.

Possible solution is [here:](https://github.com/Unity-Technologies/video-recorder/pull/2)

**Comment by chriselion** [comment]
Thanks, I'll look into this today.

**Comment by chriselion** [comment]
Thanks for catching this, I implemented basically the same fix in https://github.com/Unity-Technologies/video-recorder/pull/3.
