### ISSUE TITLE
Problems compiling RayPerceptionTest after updating to 0.8.1

### ISSUE THREAD

**Issue by DannyFriky** [Unity-Technologies/ml-agents#1983]
just update to 0.8.1 and when i opened my proyect 4 errors on RayPerceptionTests.cs appears:

> Assets\ML-Agents\Editor\Tests\RayPerceptionTests.cs(16,13/56): error CS0246: The type or namespace name 'RayPerception3D' could not be found (are you missing a using directive or an assembly reference?)
> 
> Assets\ML-Agents\Editor\Tests\RayPerceptionTests.cs(30,13/56): error CS0246: The type or namespace name 'RayPerception2D' could not be found (are you missing a using directive or an assembly reference?)

i have the ML-Agents folder and Gizmos as before (but updated)

what did i miss?
