### ISSUE TITLE
Compilation issues with 3D Ball example, unsafe code

### ISSUE THREAD

**Issue by syigzaw** [Unity-Technologies/ml-agents#1553]
I'm trying to compile and run the 3D Ball example, but I get the following compilation errors:

`Assets\ML-Agents\Scripts\InferenceBrain\TFSharpInferenceEngine.cs(105,43): error CS0227: Unsafe code may only appear if compiling with /unsafe. Enable "Allow 'unsafe' code" in Player Settings to fix this error.`
`Assets\ML-Agents\Scripts\InferenceBrain\TFSharpInferenceEngine.cs(109,43): error CS0227: Unsafe code may only appear if compiling with /unsafe. Enable "Allow 'unsafe' code" in Player Settings to fix this error.`

When I allowed unsafe, Unity would crash after about a minute or so. I know there was another issue opened that had the same issue, but the solution to that was to change the .gitignore file, and those changes are already present in mine.

Also, this may or may not be related, but when I click on the 3DBallLearning.asset file under 3DBall/Brains, I get a warning saying I need to install TensorflowSharp and add the ENABLE_TENSORFLOW flag. I had already imported the 0.5 version of TensorflowSharp and added the flag, so I don't know why this is still appearing. Could somebody please help with these two issues? Thanks in advance.

**Comment by CalvinGreen** [comment]
make sure you install tensorflow-sharp afterwards . This is always my main issue while debugging newer versions of ML-Agents


-----Original Message-----

**Comment by syigzaw** [comment]
Maybe I'm missing something, but what exactly do you mean by install? I ran the downloaded Unity TensorflowSharp plugin file and it put a bunch of files in the project I had open. Then I added the ENABLE_TENSORFLOW flag. Do I need to do anything after this?

**Comment by Retardhunter** [comment]
Restart computer and Unity? Check if unsafe is really allowed. My TS is from https://s3.amazonaws.com/unity-ml-agents/0.5/TFSharpPlugin.unitypackage.

**Comment by syigzaw** [comment]
I restarted my computer and Unity, and it still occurs. If you check those two lines in the file mentioned in the above errors, they're both function signatures that are marked unsafe. I have no idea why that's there. When I take out the unsafes, I get an error saying
`Assets\ML-Agents\Scripts\InferenceBrain\TFSharpInferenceEngine.cs(109,43): error CS0214: Pointers and fixed size buffers may only be used in an unsafe context`
So I don't think removing the unsafes is the answer.

**Comment by Retardhunter** [comment]
I dont want you to remove unsafe, also pointers are defined to be only in unsafe. But have you really allowed unsafe code checkbox in edit --> player settings?

**Comment by superjayman** [comment]
Same Here..

**Comment by mmattar** [comment]
@syigzaw / @superjayman - what version of ML-Agents and Unity are you using?

**Comment by syigzaw** [comment]
Unity: 2018.3.0f2
ML-Agents: 0.6

**Comment by eblabs** [comment]
Same for me ^^

**Comment by MarcoMeter** [comment]
Try it with Unity 2018.2.20f

**Comment by syigzaw** [comment]
I just tried it with Unity 2018.2.20f1 and the same thing happened.

**Comment by aznshodan** [comment]
having the same issue with Unity 2019.2.7f1 on Ubuntu 18.04

**Comment by snard6** [comment]
I also ran into this problem. I was not able to get this working with 2018.3.1f1 or 20128.2.20r1 (even with allowing 'unsafe' code), but finally was successful with 2017.4.18f.

**Comment by BenoitGeslain** [comment]
Going back to Unity 2017.4.10f1 worked (2017.4.18f not available on Linux)

**Comment by syigzaw** [comment]
I just tried this with Unity 2018.2.0f2, and with ML-Agents 0.4. This worked for me, and I was able to train the 3D Ball model. When I tried with the same Unity and ML-Agents 0.6, Unity didn't crash after I allowed unsafe code, but it did crash after I tried to train the brain externally. I followed the instructions here:
[https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md
](url)
After I clicked the play button, Unity crashed.

**Comment by i3games** [comment]
Same problem here, looks like ML Agents 0.6 is incompatible with Unity 2018.x

**Comment by mmattar** [comment]
Thanks for the input everyone. We've updated ML-Agents to v0.7 which changes our inference engine. This should fix this issue. Please give it a go and submit a new issue if you continue facing issues (which should be different from the ones here).
