### ISSUE TITLE
Error after migrating from 0.6 to 0.7

### ISSUE THREAD

**Issue by AdhamAlHarazi** [Unity-Technologies/ml-agents#1892]
I have the following error after I migrated from 0.6 to 0.7.
 
I installed mlagents through pip3 install -e .
I copied the new Mlagents and Gizmos folders into game assets

and I receive this error:-

Assets/ML-Agents/Scripts/InferenceBrain/BarracudaModelParamLoader.cs(7,22): error CS0234: The type or namespace name 'Remoting' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)

**Comment by AdhamAlHarazi** [comment]
Ok I followed the fix in here: https://github.com/Unity-Technologies/ml-agents/pull/1869/files/3f8ddeffd146b8910fafb2d77f83e4a06ddcaf3a

And it solved the problem
